### ISSUE TITLE
Crash on android 14

### ISSUE THREAD

**Issue by firdiar-mita** [TLabAltoh/TLabWebView#3]
```
07/02 14:51:46.717 17072 17072 Error AndroidRuntime java.lang.SecurityException: games.mita.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Parcel.createException(Parcel.java:3041)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:3024)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:2966)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6203)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at com.tlab.libwebview.UnityConnect.lambda$initWebView$1$com-tlab-libwebview-UnityConnect(UnityConnect.java:618)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at com.tlab.libwebview.UnityConnect$$ExternalSyntheticLambda29.run(Unknown Source:2)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:958)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:224)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:318)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8780)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
07/02 14:51:46.717 17072 17072 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

mostlikely because of this
com.tlab.libwebview.UnityConnect.lambda$initWebView$1$com-tlab-libwebview-UnityConnect(UnityConnect.java:618)

**Comment by firdiar-mita** [comment]
i put my solution here
https://github.com/TLabAltoh/TLabWebViewPlugin/issues/1

**Comment by TLabAltoh** [comment]
Hi @firdiar-mita, thanks for the bug report and support. I can reproduce the bug and have now publishe a fixed version.
